### ISSUE TITLE
Choosing exit before logging in gives C:\Program Files\dotnet\dotnet.exe (process 83192) exited with code 0. To automatically close the console when debugging stops, enable Tools->Options->Debugging->Automatically close the console when debugging stops. Press any key to close this window . . .

### ISSUE THREAD

**Issue by saraswathidatar** [pdx-cs-lbryan/ftpclient#2] opened 2019-07-26 05:23 UTC

**Comment by pdx-cs-lbryan** [comment] 2019-07-26 06:44
This looks like more of a developer thing? Exiting with code 0 should indicate that the program ran and exited successfully. It looks like visual studio's debugging tools keep the window open, and the message is informing you that there is an option to turn off this behavior.

I can confirm that following the given steps and choosing exit closes the window as expected, but perhaps there's a benefit to keeping the window open? 

As this isn't really a code issue, I'm closing the issue. Feel free to reopen it if you feel that it's unresolved.

**Closed as completed by pdx-cs-lbryan** 2019-07-26 06:44 UTC
